// <auto-generated />
using System;
using DXApplication2.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DXApplication2.Main.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717171559_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("DXApplication2.Common.Models.AnalysisParams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashParamsPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataRecordId");

                    b.ToTable("AnalysisParamss");
                });

            modelBuilder.Entity("DXApplication2.Common.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultPlotTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("DXApplication2.Common.Models.CollectionMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("DataGroupId");

                    b.ToTable("CollectionMembers");
                });

            modelBuilder.Entity("DXApplication2.Common.Models.DataFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderPath")
                        .IsUnique();

                    b.ToTable("DataFolders");
                });

            modelBuilder.Entity("DXApplication2.Common.Models.DataGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CsvHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("CsvPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExperimentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Extras")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataGroups");
                });

            modelBuilder.Entity("DXApplication2.Common.Models.DataRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExptParams")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultPath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ResultQuantity")
                        .HasColumnType("REAL");

                    b.Property<string>("RowIndex")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataGroupId");

                    b.ToTable("DataRecords");
                });

            modelBuilder.Entity("DXApplication2.Common.Models.ExperimentParams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExperimentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentTypeId");

                    b.HasIndex("FieldName")
                        .IsUnique();

                    b.ToTable("ExperimentParamss");
                });

            modelBuilder.Entity("DXApplication2.Common.Models.ExperimentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultPlotTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExperimentTypes");
                });

            modelBuilder.Entity("DXApplication2.Common.Models.GroupExperimentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExperimentTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DataGroupId");

                    b.HasIndex("ExperimentTypeId");

                    b.ToTable("GroupExperimentTypes");
                });

            modelBuilder.Entity("DXApplication2.Common.Models.AnalysisParams", b =>
                {
                    b.HasOne("DXApplication2.Common.Models.DataRecord", "DataRecord")
                        .WithMany("Analysis")
                        .HasForeignKey("DataRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataRecord");
                });

            modelBuilder.Entity("DXApplication2.Common.Models.CollectionMember", b =>
                {
                    b.HasOne("DXApplication2.Common.Models.Collection", "Collection")
                        .WithMany("CollectionMember")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DXApplication2.Common.Models.DataGroup", "DataGroup")
                        .WithMany("CollectionMember")
                        .HasForeignKey("DataGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("DataGroup");
                });

            modelBuilder.Entity("DXApplication2.Common.Models.DataRecord", b =>
                {
                    b.HasOne("DXApplication2.Common.Models.DataGroup", "DataGroup")
                        .WithMany("Term")
                        .HasForeignKey("DataGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataGroup");
                });

            modelBuilder.Entity("DXApplication2.Common.Models.ExperimentParams", b =>
                {
                    b.HasOne("DXApplication2.Common.Models.ExperimentType", "ExperimentType")
                        .WithMany()
                        .HasForeignKey("ExperimentTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ExperimentType");
                });

            modelBuilder.Entity("DXApplication2.Common.Models.GroupExperimentType", b =>
                {
                    b.HasOne("DXApplication2.Common.Models.DataGroup", "DataGroup")
                        .WithMany("GroupExperimentTypes")
                        .HasForeignKey("DataGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DXApplication2.Common.Models.ExperimentType", "ExperimentType")
                        .WithMany("GroupExperimentType")
                        .HasForeignKey("ExperimentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataGroup");

                    b.Navigation("ExperimentType");
                });

            modelBuilder.Entity("DXApplication2.Common.Models.Collection", b =>
                {
                    b.Navigation("CollectionMember");
                });

            modelBuilder.Entity("DXApplication2.Common.Models.DataGroup", b =>
                {
                    b.Navigation("CollectionMember");

                    b.Navigation("GroupExperimentTypes");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("DXApplication2.Common.Models.DataRecord", b =>
                {
                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("DXApplication2.Common.Models.ExperimentType", b =>
                {
                    b.Navigation("GroupExperimentType");
                });
#pragma warning restore 612, 618
        }
    }
}
