<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DevExpress.Wpf" Version="24.1.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.29" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
    <PackageReference Include="nunit" Version="3.13.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DXApplication2.Common\DXApplication2.Common.csproj" />
    <ProjectReference Include="..\DXApplication2.Main\DXApplication2.Main.csproj" />
    <ProjectReference Include="..\DXApplication2.Modules\DXApplication2.Modules.csproj" />
  </ItemGroup>

</Project>
