<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DevExpress.Wpf" Version="24.1.5" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.13.0.20260627" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DXApplication2.Common\DXApplication2.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\PlotModuleView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\ProgressSplashScreen.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
